import { Sparkles, RefreshCw, Download, AlertCircle } from 'lucide-react'
import ReactMarkdown from 'react-markdown'

export default function AIReportSection({ report, loading, error, onGenerate, onRegenerate, onDownload }) {
  if (loading) {
    return (
      <div className="f1-card">
        <div className="flex flex-col items-center justify-center py-12 gap-4">
          <div className="w-10 h-10 border-2 border-f1-gray border-t-f1-red rounded-full animate-spin" />
          <p className="text-gray-400 text-sm">Groq AI is analyzing the race...</p>
          <p className="text-gray-600 text-xs">This usually takes 10–20 seconds</p>
        </div>
      </div>
    )
  }

  if (!report) {
    return (
      <div className="f1-card border-dashed">
        <div className="flex flex-col items-center justify-center py-12 gap-4 text-center">
          <div className="w-14 h-14 rounded-full bg-f1-red/10 border border-f1-red/30 flex items-center justify-center">
            <Sparkles size={24} className="text-f1-red" />
          </div>
          <div>
            <p className="text-white font-semibold">AI Race Report</p>
            <p className="text-gray-500 text-sm mt-1">
              Generate a professional race analysis powered by Groq AI
            </p>
          </div>
          {error && (
            <div className="flex items-center gap-2 text-red-400 text-sm bg-red-950/30 px-4 py-2 rounded-lg">
              <AlertCircle size={14} /> {error}
            </div>
          )}
          <button className="btn-primary" onClick={onGenerate}>
            <Sparkles size={16} /> Generate AI Report
          </button>
        </div>
      </div>
    )
  }

  return (
    <div className="f1-card">
      <div className="flex items-center justify-between mb-6 flex-wrap gap-3">
        <div>
          <h2 className="section-heading mb-1">AI Race Report</h2>
          <p className="text-gray-600 text-xs">
            Generated by {report.modelUsed} ·{' '}
            {report.generatedAt ? new Date(report.generatedAt).toLocaleDateString() : ''}
          </p>
        </div>
        <div className="flex gap-2 flex-wrap">
          <button className="btn-secondary text-sm py-2" onClick={onRegenerate}>
            <RefreshCw size={14} /> Regenerate
          </button>
          <button className="btn-primary text-sm py-2" onClick={onDownload}>
            <Download size={14} /> Export PDF
          </button>
        </div>
      </div>
      <div className="report-content prose prose-invert max-w-none">
        <ReactMarkdown>{report.reportContent}</ReactMarkdown>
      </div>
    </div>
  )
}