const PDFDocument = require('pdfkit');

function generatePDF(report, res) {
  const doc = new PDFDocument({
    size:    'A4',
    margins: { top: 60, bottom: 60, left: 60, right: 60 },
  });

  // Set response headers so browser knows it's a downloadable PDF
  const filename = `F1_Report_${report.season}_Round${report.round}.pdf`;
  res.setHeader('Content-Type', 'application/pdf');
  res.setHeader('Content-Disposition', `attachment; filename="${filename}"`);

  // Pipe the PDF directly to the HTTP response
  doc.pipe(res);

  doc
    .fillColor('#e10600') // F1 red
    .fontSize(24)
    .font('Helvetica-Bold')
    .text('🏎 F1 RACE REPORT', { align: 'center' });

  doc
    .fillColor('#333333')
    .fontSize(16)
    .font('Helvetica-Bold')
    .text(report.race_name, { align: 'center' });

  doc
    .fillColor('#666666')
    .fontSize(11)
    .font('Helvetica')
    .text(`Season ${report.season} · Round ${report.round}`, { align: 'center' });

  doc
    .fillColor('#666666')
    .fontSize(10)
    .text(`Generated on ${new Date().toLocaleDateString('en-GB', {
      day: 'numeric', month: 'long', year: 'numeric'
    })}`, { align: 'center' });

  doc.moveDown(0.5);
  doc
    .strokeColor('#e10600')
    .lineWidth(2)
    .moveTo(60, doc.y)
    .lineTo(535, doc.y)
    .stroke();

  doc.moveDown(1);

  const lines = report.content.split('\n');

  lines.forEach(line => {
    if (line.startsWith('# ')) {
      doc
        .fillColor('#e10600')
        .fontSize(18)
        .font('Helvetica-Bold')
        .text(line.replace('# ', ''), { paragraphGap: 6 });
      doc.moveDown(0.3);

    } else if (line.startsWith('## ')) {
      doc.moveDown(0.5);
      doc
        .fillColor('#333333')
        .fontSize(14)
        .font('Helvetica-Bold')
        .text(line.replace('## ', ''), { paragraphGap: 4 });
      doc.moveDown(0.2);

    } else if (line.startsWith('### ')) {
      doc
        .fillColor('#555555')
        .fontSize(12)
        .font('Helvetica-Bold')
        .text(line.replace('### ', ''), { paragraphGap: 3 });

    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      doc
        .fillColor('#333333')
        .fontSize(10)
        .font('Helvetica')
        .text(`• ${line.replace(/^[-*] /, '')}`, {
          indent: 15,
          paragraphGap: 2,
        });

    } else if (line.trim() === '') {
      doc.moveDown(0.4);

    } else {
      const cleanLine = line.replace(/\*\*(.*?)\*\*/g, '$1');
      doc
        .fillColor('#333333')
        .fontSize(10)
        .font('Helvetica')
        .text(cleanLine, { paragraphGap: 3, lineGap: 2 });
    }
  });

  doc.moveDown(2);
  doc
    .strokeColor('#e10600')
    .lineWidth(1)
    .moveTo(60, doc.y)
    .lineTo(535, doc.y)
    .stroke();

  doc.moveDown(0.5);
  doc
    .fillColor('#999999')
    .fontSize(9)
    .font('Helvetica')
    .text('Generated by F1 Race Report Tool · Powered by Groq AI', {
      align: 'center',
    });

  doc.end();
}

module.exports = { generatePDF };